=== mooshak-dcc/mooshak-2/WebContent/WEB-INF/classes/pt/up/fc/dcc/eshu/client/eshugwt/config/EshuConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/EshuConfig"
	xmlns:conf="http://www.example.org/EshuConfig" elementFormDefault="qualified">-->
<schema 
	targetNamespace="http://www.example.org/EshuConfig" 
	elementFormDefault="qualified"
	xmlns="http://www.w3.org/2001/XMLSchema" 
	xmlns:conf="http://www.example.org/EshuConfig">

<element name="eshu" type="conf:Eshu"></element>

<complexType name="Eshu">
	<sequence>
		
		<element name="style" type="conf:Style"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="diagram" type="conf:Diagram"
				maxOccurs="1" minOccurs="1">
		</element>
		
	</sequence>
</complexType >

<complexType name="Style">
	<all>
		<element name="editorStyle" type="conf:Editor_style"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="toolbarStyle" type="conf:Toolbar_style"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="vertice" type="conf:Vertice"
				maxOccurs="1" minOccurs="1">
		</element>
	
		<element name="textBox" type="conf:Text_box"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="validation_syntaxe" type="boolean"
				maxOccurs="1" minOccurs="1">
		</element>
	
	</all>

</complexType>


<complexType name="Editor_style">
	<attribute name="width" type="integer" use="required"   />
	<attribute name="height" type="integer" use="required"   />
	<attribute name="borderWidth" type="integer" use="required"   />
	<attribute name="borderColor" type="string" use="required"   />
	<attribute name="background" type="string" use="required"   />
	<attribute name="gridVisible" type="boolean" use="required"   />
	<attribute name="gridColorLine" type="string" use="required"   />
		
</complexType>

<complexType name="Toolbar_style">
	<attribute name="width" type="integer" use="required"   />
	<attribute name="height" type="integer" use="required"   />
	<attribute name="borderWidth" type="integer" use="required"   />
	<attribute name="borderColor" type="normalizedString" use="required"   />
	<attribute name="background" type="normalizedString" use="required"   />
	<attribute name="position" type="normalizedString" use="required"   />
	
</complexType>



<complexType name="Vertice">

	<attribute name="width" type="integer" use="required"   />
	<attribute name="height" type="integer" use="required"   />
	<attribute name="background" type="normalizedString" use="required"   />
	<attribute name="backgroundSelected" type="normalizedString" use="required"   />
	<attribute name="borderWidth" type="integer" use="required"   />
	<attribute name="borderColor" type="normalizedString" use="required"   />

</complexType>
   
   
   <complexType name="Text_box">
   	<attribute name="font" type="normalizedString" use="required"   />
   	<attribute name="color" type="normalizedString" use="required"   />
   	<attribute name="colorSelected" type="normalizedString" use="required"   />
   	<attribute name="align" type="normalizedString" use="required"   />
   	<attribute name="spacing" type="normalizedString" use="required"   />
   	<attribute name="backgroundSelected" type="normalizedString" use="required"   />
   	
   		
   </complexType>
   
   
 

<complexType name="Diagram">
	
	<sequence>
		<element name="nodeTypes" type="conf:Node_types"
				maxOccurs="unbounded" minOccurs="1">
		</element>
		
		<element name="edgeTypes" type="conf:Edge_types"
				maxOccurs="unbounded" minOccurs="1">
		</element>
	</sequence>
	<attribute name="name" type="string" use="required" />
	<attribute name="pathFile" type="string" use="required" />
	
</complexType>

<complexType name="Node_types">

	<sequence>
		<element name="nodeConfig" type="conf:Node_config"
				maxOccurs="unbounded" minOccurs="1">
		</element>
	</sequence>
</complexType>


<complexType name="Node_config">

	<sequence>
	
		<element name="type" type="string"
				maxOccurs="1" minOccurs="1" default="class">
		</element>
		
		<element name="iconTollbarSVGPath" type="string"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="imgSVGPath" type="string"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="label" type="conf:Label"
				maxOccurs="1" minOccurs="1">
		</element>
		<element name="containers" type="conf:Containers"
				maxOccurs="1" minOccurs="0">
		</element>
		
		<element name="stereotype" type="string"
				maxOccurs="1" minOccurs="0">
		</element>
		<element name="variant" type="string"
				maxOccurs="1" minOccurs="1" default="class">
		</element>
		
		<element name="isConfigurable" type="boolean"
				maxOccurs="1" minOccurs="1" default="true">
		</element>
		
		<element name="includeElement" type="boolean"
				maxOccurs="1" minOccurs="1" default="true">
		</element>
		
		<element name="infoUrlNode" type="conf:Info_url"
				maxOccurs="1" minOccurs="1" >
		</element>
		
		<!--  
			7	0	1   	northwest	north		northeast
			6	8	2		west		center		east
			5	4	3		southwest 	south 		southeast
		 -->		
		<element name="anchors" type="conf:Anchors"
				maxOccurs="1" minOccurs="1"  >
		</element>
		
		
		<element name="propertiesNode" type="conf:Properties"
				maxOccurs="1" minOccurs="1">
		</element>
		
		
		<element name="featuresNode" type="conf:Features"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="connects" type="conf:Connects"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="degreeIn" type="string"
				maxOccurs="1" minOccurs="1">
		</element>
		<element name="degreeOut" type="string"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="nodeStyle" type="conf:Node_style" 
				maxOccurs="1" minOccurs="1"  > 
		</element>
		
	</sequence>
	
</complexType>

<complexType name="Anchors">
		<sequence>
		<element name="anchor" type="conf:Anchor"
				maxOccurs="unbounded" minOccurs="1">
		</element>
		</sequence>

</complexType>

<complexType name="Anchor">
	<attribute name="position" type="string" use="required" />
</complexType>


<complexType name="Features">
	<sequence>
		<element name="feature" type="conf:Feature"
				maxOccurs="unbounded" minOccurs="0">
		</element>
	</sequence>
</complexType>


<complexType name="Properties">
	<sequence>
		<element name="property" type="conf:Property"
				maxOccurs="unbounded" minOccurs="1">
		</element>
	</sequence>
</complexType>


<complexType name="Property">
  <attribute name="name" type="string" use="required" />
  <attribute name="type" type="string" use="required" />
  <attribute name="typeShow" type="string" use="required" />
  <attribute name="disabled" type="string" use="required" />
  <attribute name="view" type="boolean" use="required" />
  <attribute name="impExp" type="boolean" use="required" />
  
</complexType>



<complexType name="Label">
	<all>
	<element name="underlined" type="conf:Underlined"
				maxOccurs="1" minOccurs="1">
	</element>
	
	</all>
  <attribute name="defaultValue" type="string" use="required" />
  <attribute name="position" type="string" use="required" />
  <attribute name="letterCase" type="string" use="required" />
  <attribute name="firstLetterCase" type="string" use="required" />
  <attribute name="disabled" type="boolean" use="required" />
  <attribute name="alignment" type="string"  />
</complexType>

<complexType name="Containers">
	<sequence>
		<element name="container" type="conf:Container"
				maxOccurs="unbounded" minOccurs="1">
		</element>
	</sequence>
</complexType>

<complexType name="Container">
	<sequence>
		<element name="field" type="conf:Field"
				maxOccurs="unbounded" minOccurs="1">
		</element>
		
	</sequence>
	 <attribute name="name" type="string" use="required" />
	 <attribute name="pather" type="string" use="required" />
	 <attribute name="alignment" type="string" use="required" />
	 <attribute name="underlined" type="string" use="required" />
	 <attribute name="default_text" type="string" use="required" />
	 <attribute name="textbox_default_number" type="string" use="required" />
	 
		
</complexType>

<complexType name="Field">
 <attribute name="value" type="string" use="required" />
 <attribute name="name" type="string" use="required" />
</complexType>


<complexType name="Underlined">
 <attribute name="value" type="string" use="required" />
 <attribute name="controler" type="string" use="required" />
</complexType>


<complexType name="Feature">
  <attribute name="name" type="string" use="required" />
  <attribute name="type" type="string" use="required" />
   <attribute name="value" type="string" use="required" />
   <attribute name="view" type="boolean" use="required" />
  <attribute name="impExp" type="boolean" use="required" />
   <attribute name="imgPath" type="string" use="optional" />
  
</complexType>

<complexType name="Info_url">
	<sequence>
		<element name="url" type="string"
				maxOccurs="unbounded" minOccurs="1">
		</element>
	</sequence>
</complexType>

<complexType name="Connects">
	<sequence>
 	<element name="connect" type="conf:Connect"
				maxOccurs="unbounded" minOccurs="1">
	</element>
	</sequence>
</complexType>

<complexType name="Node_style">
	<attribute name="autoresize" type="boolean" use="required"   />
</complexType>


<complexType name="Connect">
 	<attribute name="with" type="string" use="required" />
 	<attribute name="to" type="string" use="required" />
 	<attribute name="max" type="string" use="required" />
 	<attribute name="min" type="string" use="required" />
</complexType>

<complexType name="Edge_types">
	<sequence>
		<element name="edgeConfig" type="conf:Edge_config"
				maxOccurs="unbounded" minOccurs="1">
		</element>
	</sequence>
</complexType>


<complexType name="Edge_config">
	<sequence>
		<element name="type" type="string"
				maxOccurs="1" minOccurs="1" default="class">
		</element>
		
		<element name="iconTollbarSVGPath" type="string"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="lineDuple" type="boolean"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="lineDash" type="boolean"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="label" type="conf:Label"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="variant" type="string"
				maxOccurs="1" minOccurs="1" default="class">
		</element>
		
		<element name="isConfigurable" type="boolean"
				maxOccurs="1" minOccurs="1" default="true">
		</element>
		
		<element name="infoUrlEdge" type="conf:Info_url"
				maxOccurs="1" minOccurs="1" >
		</element>
		
		<element name="propertiesEdge" type="conf:Properties"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="featuresEdge" type="conf:Features"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="cardinality" type="boolean"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="headSource" type="conf:Head_Edge"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="headTarget" type="conf:Head_Edge"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="stereotype" type="string"
				maxOccurs="1" minOccurs="0">
		</element>
		
		
		
	</sequence>
</complexType>


<complexType name="Head_Edge">
	<attribute name="type" type="string" use="required" />
 	<attribute name="fill" type="string" use="required" />
 	<attribute name="dash" type="string" use="required" />
</complexType>


</schema>

=== mooshak-dcc/mooshak-2/WebContent/WEB-INF/classes/pt/up/fc/dcc/eshu/client/eshugwt/config/EERConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<eshu xmlns="http://www.example.org/EshuConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/EshuConfig EshuConfig.xsd ">
  <style>
    <editorStyle width="1000" height="700" borderWidth="1" 
          borderColor="#000" background="#FFFFFF"  
          gridVisible="false" gridColorLine="#c0c0c0"/>
    
    <toolbarStyle width="500" height="300" borderWidth="1"
       				borderColor="black" background="WhiteSmoke"
       				position="vertical"  />
      
    <vertice width="70" height="40" background="white"
        		backgroundSelected="blue" borderWidth="1" borderColor="red"/> 
      
    <textBox font="Georgia" color="Green" colorSelected="Black" align="left"
        		spacing="3px" backgroundSelected="Blue"/>
    <validation_syntaxe>false</validation_syntaxe> 
    
  </style>
  
   <diagram name="EER" pathFile="./EERConfig.xml">
    <nodeTypes>
    
      <nodeConfig>
        <type>Attribute</type>
        <iconTollbarSVGPath>./image/eer/atributo.svg</iconTollbarSVGPath>
        <imgSVGPath>./image/eer/atributo.svg</imgSVGPath>
         <label defaultValue="Attribute" firstLetterCase="lowercase" letterCase="lowercase" position="center" disabled="false" alignment="center" >
         <underlined controler="none" value="0"/>
        </label>
        <variant>Attribute</variant>
        <isConfigurable>true</isConfigurable>
        <includeElement>false</includeElement>
         <infoUrlNode>
         	<url>http://www.dcc.fc.up.pt/~fds/aulas/BD/1516/Slides/parteII.pdf</url>
         	<url>https://www.google.pt</url>
         </infoUrlNode>
         <anchors> 
             <anchor  position="north"/>
             <anchor  position="south"/> 
             <anchor  position="east"/>
             <anchor  position="west"/> 
         </anchors>
        <propertiesNode> 
          <property name="type" type="String" typeShow="input" disabled="true" impExp="true" view="true"  />
	      <property name="id" type="Number" typeShow="input" disabled="true" impExp="true" view="true" /> 
          <property name="x" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="y" type="Number" typeShow="input" disabled="false" impExp="true" view="true" />
	      <property name="width" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="height" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="label" type="String" typeShow="input" disabled="false" impExp="true" view="true"/> 
        </propertiesNode>
        <featuresNode>
        </featuresNode>
        <connects>
          <connect max="unbounded" min="0" to="Entity" with="Line"/> 
          <connect max="unbounded" min="0" to="EntityWeak" with="Line"/>
	 	  <connect max="unbounded" min="0" to="Attribute" with="Line"/> 
          <connect max="unbounded" min="0" to="AttributeDerived" with="Line"/>
          <connect max="unbounded" min="0" to="AttributeMultivalue" with="Line"/>
          <connect max="unbounded" min="0" to="AttributeKey" with="Line"/>
          <connect max="unbounded" min="0" to="AttributeKeyWeak" with="Line"/>
          <connect max="unbounded" min="0" to="Relationship" with="Line"/>
          <connect max="unbounded" min="0" to="WeakRelationship" with="Line"/>
        </connects> 
        <degreeIn>unbounded</degreeIn>
        <degreeOut>unbounded</degreeOut>
        <nodeStyle autoresize="true"/>
      </nodeConfig>
      
     <nodeConfig>
        <type>AttributeDerived</type>
        <iconTollbarSVGPath>./image/eer/atributo_derivado_icon.svg</iconTollbarSVGPath>
        <imgSVGPath>./image/eer/atributo_derivado.svg</imgSVGPath>
         <label defaultValue="Attribute" firstLetterCase="lowercase" letterCase="lowercase" position="center" disabled="false" alignment="center">
         <underlined controler="none" value="0"/>
        </label>
        <variant>Attribute</variant>
        <isConfigurable>true</isConfigurable>
        <includeElement>false</includeElement>
         <infoUrlNode>
         	<url>http://www.dcc.fc.up.pt/~fds/aulas/BD/1516/Slides/parteII.pdf</url>
         	<url>https://www.google.pt</url>
         </infoUrlNode>
         <anchors> 
             <anchor  position="north"/>
             <anchor  position="south"/> 
             <anchor  position="east"/>
             <anchor  position="west"/> 
         </anchors>
        <propertiesNode> 
          <property name="type" type="String" typeShow="input" disabled="true" impExp="true" view="true"  />
	      <property name="id" type="Number" typeShow="input" disabled="true" impExp="true" view="true" /> 
          <property name="x" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="y" type="Number" typeShow="input" disabled="false" impExp="true" view="true" />
	      <property name="width" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="height" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="label" type="String" typeShow="input" disabled="false" impExp="true" view="true"/> 
        </propertiesNode>
        <featuresNode>
        </featuresNode>
        <connects>
          <connect max="1" min="0" to="Attribute" with="Line"/> 
          <connect max="1" min="0" to="Entity" with="Line"/> 
          <connect max="1" min="0" to="EntityWeak" with="Line"/> 
          <connect max="1" min="0" to="Relationship" with="Line"/>
          <connect max="1" min="0" to="WeakRelationship" with="Line"/>
          
        </connects>
        <degreeIn>1</degreeIn>
        <degreeOut>1</degreeOut>
        <nodeStyle autoresize="true"/>
      </nodeConfig>
     
      <nodeConfig>
       
        <type>AttributeMultivalue</type>
        <iconTollbarSVGPath>./image/eer/atributo_multivalor_icon.svg</iconTollbarSVGPath>
        <imgSVGPath>./image/eer/atributo_multivalor.svg</imgSVGPath>
         <label defaultValue="Attribute" firstLetterCase="lowercase" letterCase="lowercase" position="center" disabled="false" alignment="center">
         <underlined controler="none" value="0"/>
        </label>
        <variant>Attribute</variant>
        <isConfigurable>true</isConfigurable>
        <includeElement>false</includeElement>
         <infoUrlNode>
         	<url>http://www.dcc.fc.up.pt/~fds/aulas/BD/1516/Slides/parteII.pdf</url>
         	<url>https://www.google.pt</url>
         </infoUrlNode>
         <anchors> 
             <anchor  position="north"/>
             <anchor  position="south"/> 
             <anchor  position="east"/>
             <anchor  position="west"/> 
         </anchors>
        <propertiesNode> 
          <property name="type" type="String" typeShow="input" disabled="true" impExp="true" view="true"  />
	      <property name="id" type="Number" typeShow="input" disabled="true" impExp="true" view="true" /> 
          <property name="x" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="y" type="Number" typeShow="input" disabled="false" impExp="true" view="true" />
	      <property name="width" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="height" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="label" type="String" typeShow="input" disabled="false" impExp="true" view="true"/> 
        </propertiesNode>
        <featuresNode>
        </featuresNode>
        <connects>
          <connect max="1" min="0" to="Attribute" with="Line"/>   
          <connect max="1" min="0" to="Entity" with="Line"/> 
          <connect max="1" min="0" to="EntityWeak" with="Line"/> 
          <connect max="1" min="0" to="Relationship" with="Line"/>
          <connect max="1" min="0" to="WeakRelationship" with="Line"/>
        </connects>
        
        <degreeIn>1</degreeIn>
        <degreeOut>1</degreeOut>
        <nodeStyle autoresize="true"/>
        
      </nodeConfig> 
      
      
      <nodeConfig>
       <type>AttributeKey</type>
        <iconTollbarSVGPath>./image/eer/atributoChave.svg</iconTollbarSVGPath>
        <imgSVGPath>./image/eer/atributo.svg</imgSVGPath>
         <label defaultValue="Attribute" firstLetterCase="lowercase" letterCase="lowercase" position="center" disabled="false" alignment="center" >
         <underlined controler="none" value="1"/>
        </label>
        <variant>Attribute</variant>
        <isConfigurable>true</isConfigurable>
        <includeElement>false</includeElement>
         <infoUrlNode>
         	<url>http://www.dcc.fc.up.pt/~fds/aulas/BD/1516/Slides/parteII.pdf</url>
         	<url>https://www.google.pt</url>
         </infoUrlNode>
         <anchors> 
             <anchor  position="north"/>
             <anchor  position="south"/> 
             <anchor  position="east"/>
             <anchor  position="west"/> 
         </anchors>
        <propertiesNode> 
          <property name="type" type="String" typeShow="input" disabled="true" impExp="true" view="true"  />
	      <property name="id" type="Number" typeShow="input" disabled="true" impExp="true" view="true" /> 
          <property name="x" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="y" type="Number" typeShow="input" disabled="false" impExp="true" view="true" />
	      <property name="width" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="height" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="label" type="String" typeShow="input" disabled="false" impExp="true" view="true"/> 
        </propertiesNode>
        <featuresNode>
        </featuresNode>
        <connects>
