=== mooshak-dcc/mooshak-2/WebContent/WEB-INF/classes/pt/up/fc/dcc/eshu/client/eshugwt/config2/DL2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/dl2"
	xmlns:conf="http://www.example.org/EshuConfig" elementFormDefault="qualified">-->
<schema 
	targetNamespace="http://www.example.org/EshuConfig" 
	elementFormDefault="qualified"
	xmlns="http://www.w3.org/2001/XMLSchema" 
	xmlns:conf="http://www.example.org/EshuConfig">

<element name="dl2" type="conf:DL2"></element>

<complexType name="DL2">
	<sequence>
	
		<element name="style" type="conf:Style"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="diagram" type="conf:Diagram"
				maxOccurs="1" minOccurs="1">
		</element>
		
	</sequence>
</complexType >

<complexType name="Style">
	<all>
		<element name="editorStyle" type="conf:Editor_style"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="toolbarStyle" type="conf:Toolbar_style"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="windowsProperties" type="conf:WindowsProperties" 
				maxOccurs="1" minOccurs="1">
		</element>
	
	</all>

</complexType>


<complexType name="Editor_style">
	<attribute name="width" type="integer" use="required"   />
	<attribute name="height" type="integer" use="required"   />
	<attribute name="borderWidth" type="integer" use="required"   />
	<attribute name="borderColor" type="string" use="required"   />
	<attribute name="background" type="string" use="required"   />
	<attribute name="gridVisible" type="boolean" use="required"   />
	<attribute name="gridColorLine" type="string" use="required"   />
		
</complexType>

	<complexType name="Toolbar_style">
		<attribute name="width" type="integer" use="required" />
		<attribute name="height" type="integer" use="required" />
		<attribute name="borderWidth" type="integer" use="required" />
		<attribute name="borderColor" type="normalizedString"
			use="required" />
		<attribute name="background" type="normalizedString"
			use="required" />
		<attribute name="position" type="normalizedString"
			use="required" />

		<attribute name="widthElement" type="integer"></attribute>
		<attribute name="heightElement" type="integer"></attribute>
	</complexType> 




	<!--  >complexType name="Vertice">

	<attribute name="width" type="integer" use="required"   />
	<attribute name="height" type="integer" use="required"   />
	<attribute name="background" type="normalizedString" use="required"   />
	<attribute name="backgroundSelected" type="normalizedString" use="required"   />
	<attribute name="borderWidth" type="integer" use="required"   />
	<attribute name="borderColor" type="normalizedString" use="required"   />

</complexType>
   
   
   <complexType name="Text_box">
   	<attribute name="font" type="normalizedString" use="required"   />
   	<attribute name="color" type="normalizedString" use="required"   />
   	<attribute name="colorSelected" type="normalizedString" use="required"   />
   	<attribute name="align" type="normalizedString" use="required"   />
   	<attribute name="margin" type="normalizedString" use="required"   />
   	<attribute name="backgroundSelected" type="normalizedString" use="required"   />
   	
   		
   </complexType-->
   
   
 

<complexType name="Diagram">
	
	<sequence>
		<element name="nodeTypes" type="conf:NodeTypes"
				maxOccurs="unbounded" minOccurs="1">
		</element>
		
		<element name="edgeTypes" type="conf:EdgeTypes"
				maxOccurs="unbounded" minOccurs="1">
		</element>
		
		<element name="syntaxeValidation" type="conf:SyntaxeValidation"
				maxOccurs="1" minOccurs="1">
		</element>
	</sequence>
	
	<attribute name="name" type="string" use="required" />
	<attribute name="extension" type="string" use="required" />
	
</complexType>



<complexType name="SyntaxeValidation">
	
	<sequence>
		<element name="reducibles" type="conf:NameType"
				maxOccurs="1" minOccurs="1">
		</element>
		<element name="componentValidation" type="conf:CompValidation"
				maxOccurs="1" minOccurs="1">
		</element>
		
	</sequence>

	<attribute name="syntaxeValidationIn" type="conf:SyntaxeVal" use="required" />
	<attribute name="nodesValidation" type="boolean" use="required" />
	<attribute name="edgesValidation" type="boolean" use="required" />
	
</complexType>


<complexType name="NameType">
	
	<sequence>
		<element name="elementType" type="string"
				maxOccurs="unbounded" minOccurs="0">
		</element>
	</sequence>
	
</complexType>


<complexType name="CompValidation">
	
	<attribute name="numberMinComponent" type="string" use="optional" />
	<attribute name="numberMaxComponent" type="string" use="optional" />
	<attribute name="disable" type="boolean" use="required" />
	
</complexType>


<complexType name="NodeTypes">

	<sequence>
	
		<element name="type" type="string"
				maxOccurs="1" minOccurs="1" default="class">
		</element>
		<element name="variant" type="string"
				maxOccurs="1" minOccurs="1" default="class">
		</element>
		
		<element name="label" type="conf:Label"
				maxOccurs="1" minOccurs="1">
		</element>
		<element name="containers" type="conf:Containers"
				maxOccurs="1" minOccurs="0">
		</element>
		
		<element name="isConfigurable" type="boolean"
				maxOccurs="1" minOccurs="1" default="true">
		</element>
		
		<element name="includeElement" type="boolean"
				maxOccurs="1" minOccurs="1" default="false">
		</element>
		
		<element name="rotation" type="boolean"
				maxOccurs="1" minOccurs="1" default="false">
		</element>
		
		<element name="infoUrlNode" type="conf:InfoUrl"
				maxOccurs="1" minOccurs="1" >
		</element>
		
		<!--  
			7	0	1   	northwest	north		northeast
			6	8	2		west		center		east
			5	4	3		southwest 	south 		southeast
		 -->
		 <element name="handlers" type="conf:Handlers"
				maxOccurs="1" minOccurs="1"  >
		</element>	
			
		<element name="anchors" type="conf:Anchors"
				maxOccurs="1" minOccurs="1"  >
		</element>
		
		<element name="propertiesNode" type="conf:Properties"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="featuresNode" type="conf:Features"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="nodeStyle" type="conf:NodeStyle" 
				maxOccurs="1" minOccurs="1"  > 
		</element>
		
		<element name="stereotype" type="conf:Stereotype"
				maxOccurs="1" minOccurs="0">
		</element>
		
		<element name="nodeValidation" type="conf:NodeValidation" 
				maxOccurs="1" minOccurs="1"  > 
		</element>
		
	</sequence>
	
</complexType>

<complexType name="Anchors">
		<sequence>
		<element name="anchor" type="conf:Anchor"
				maxOccurs="unbounded" minOccurs="1">
		</element>
		</sequence>
		<attribute name="fixed" type="boolean" use="optional" />

</complexType>

<complexType name="Handlers">
		<sequence>
		<element name="handler" type="conf:Anchor"
				maxOccurs="unbounded" minOccurs="1">
		</element>
		</sequence>

</complexType>

<complexType name="Anchor">
	<attribute name="position" type="conf:Direction" use="required" />
</complexType>


<complexType name="Features">
	<sequence>
		<element name="feature" type="conf:Feature"
				maxOccurs="unbounded" minOccurs="0">
		</element>
	</sequence>
</complexType>


<complexType name="Properties">
	<sequence>
		<element name="property" type="conf:Property"
				maxOccurs="unbounded" minOccurs="1">
		</element>
	</sequence>
</complexType>


<complexType name="Property">
  <attribute name="name" type="string" use="required" />
  <attribute name="type" type="string" use="required" />
  <attribute name="typeShow" type="string" use="required" />
  <attribute name="disabled" type="string" use="required" />
  <attribute name="view" type="boolean" use="required" />
  <attribute name="impExp" type="boolean" use="required" />
  
</complexType>



<complexType name="Label">
	<all>
	<element name="field" type="conf:Field"
				maxOccurs="1" minOccurs="1">
	</element>
	
	</all>
	  <attribute name="defaultValue" type="string" use="required" />
	  <attribute name="position" type="conf:Position" use="required" />
	  <attribute name="letterCase" type="string" use="required" />
	  <attribute name="firstLetterCase" type="string" use="required" />
	  <attribute name="disabled" type="boolean" use="required" />
	  <attribute name="alignment" type="conf:Alignment"  />
	  <attribute name="underlined" type="conf:UnderlinedValue"  />
	  <attribute name="pattern" type="string"  />
	  <attribute name="textColor" type="string" use="required"  />
	  <attribute name="textFont" type="string" use="required"  />
	  <attribute name="marginWidth" type="integer" use="required"  />
	  <attribute name="marginHeight" type="integer" use="required"  />
	  
   
</complexType>

<complexType name="Containers">
	<sequence>
		<element name="container" type="conf:Container"
				maxOccurs="unbounded" minOccurs="1">
		</element>
	</sequence>
	
	
</complexType>

<complexType name="Container">
	<sequence>
		<element name="field" type="conf:Field"
				maxOccurs="unbounded" minOccurs="1">
		</element>
	</sequence>
	 <attribute name="name" type="string" use="required" />
	 <attribute name="pattern" type="string" use="required" />
	 <attribute name="alignment" type="conf:Alignment" use="required" />
	 <attribute name="underlined" type="conf:UnderlinedValue" use="required" />
	 <attribute name="defaultText" type="string" use="required" />
	 <attribute name="numberDefaultTextbox" type="string" use="required" />
	 <attribute name="addTextBoxes" type="boolean" use="required" />
	 <attribute name="lineDash" type="boolean" use="required" />
	 <attribute name="disabled" type="boolean" use="required" />
	 
	 
		
</complexType>

<complexType name="Field">
 <attribute name="value" type="string" use="required" />
 <attribute name="name" type="string" use="required" />
</complexType>



<complexType name="Feature">
  <attribute name="name" type="string" use="required" />
  <attribute name="type" type="string" use="required" />
  <attribute name="value" type="string" use="required" />
  <attribute name="view" type="boolean" use="required" />
  <attribute name="impExp" type="boolean" use="required" />
  <attribute name="imgPath" type="string" use="optional" />
  <attribute name="source" type="boolean" use="optional" />
  <attribute name="target" type="boolean" use="optional" />
  <attribute name="nodetype" type="boolean" use="optional" />
  
</complexType>

<complexType name="InfoUrl">
	<sequence>
		<element name="url" type="string"
				maxOccurs="unbounded" minOccurs="1">
		</element>
	</sequence>
</complexType>

<complexType name="Connects">
	<sequence>
 	<element name="connect" type="conf:Connect"
				maxOccurs="unbounded" minOccurs="1">
	</element>
	</sequence>
</complexType>

<complexType name="NodeStyle">
	<attribute name="autoresize" type="boolean" use="required"   />
	<attribute name="multiElement" type="boolean" use="optional" />
	<attribute name="width" type="integer" use="required"   />
	<attribute name="height" type="integer" use="required"   />
	<attribute name="iconTollbarSVGPath" type="string" use="required" />
	<attribute name="imgSVGPath" type="string" use="required"  />
	<!--attribute name="stereotype" type="string" use="optional"  /-->
	<attribute name="roundCorner" type="int" use="optional"  />
	
	
</complexType>

<complexType name="NodeValidation">
	
	<sequence>
		<element name="connects" type="conf:Connects"
					maxOccurs="1" minOccurs="1">
		</element>
		
	</sequence>
	<attribute name="notAvailable" type="boolean" use="optional"></attribute>
	<attribute name="degreeIn" type="string" use="required" />
	<attribute name="degreeOut" type="string" use="required" />
	<attribute name="allAnchorsConnect" type="boolean" use="required"   />
</complexType>



<complexType name="Connect">
 	<attribute name="with" type="string" use="required" />
 	<attribute name="to" type="string" use="required" />
 	<attribute name="max" type="string" use="required" />
 	<attribute name="min" type="string" use="required" />
</complexType>


<complexType name="EdgeTypes">
	<sequence>
		<element name="type" type="string"
				maxOccurs="1" minOccurs="1" default="class">
		</element>
		<element name="variant" type="string"
				maxOccurs="1" minOccurs="1" default="class">
		</element>
		
		<element name="label" type="conf:Label"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="isConfigurable" type="boolean"
				maxOccurs="1" minOccurs="1" default="true">
		</element>
		
		<element name="infoUrlEdge" type="conf:InfoUrl"
				maxOccurs="1" minOccurs="1" >
		</element>
		
		<element name="propertiesEdge" type="conf:Properties"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="featuresEdge" type="conf:Features"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="cardinality" type="boolean"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="edgeStyle" type="conf:EdgeStyle"
				maxOccurs="1" minOccurs="1">
		</element>
		
	</sequence>
</complexType>


<complexType name="EdgeStyle">
	
	<sequence>
		<element name="headSource" type="conf:Head_Edge"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="headTarget" type="conf:Head_Edge"
				maxOccurs="1" minOccurs="1">
		</element>
		
		<element name="stereotype" type="conf:Stereotype"
				maxOccurs="1" minOccurs="0">
		</element>
		
	</sequence>
	<attribute name="iconTollbarSVGPath" type="string" use="required"   />
	<attribute name="lineDuple" type="boolean" use="required"   />
	<attribute name="lineDash" type="boolean" use="required"   />
</complexType>

<complexType name="Stereotype">
	<attribute name="name" type="string" use="required" />
 	<attribute name="marginHeight" type="integer" use="required" />
 	<attribute name="marginWidth" type="integer" use="required" />
 	<attribute name="position" type="conf:Position" use="required" />
</complexType>

<complexType name="Head_Edge">
	<attribute name="type" type="string" use="required" />
 	<attribute name="fill" type="string" use="required" />
 	<attribute name="dash" type="string" use="required" />
</complexType>

<complexType name="WindowsProperties">
	<attribute name="disabled" type="boolean" use="required" />
	<attribute name="startVisible" type="boolean" use="required" />
</complexType>

    <simpleType name="Position">
    	<restriction base="string">
    		<enumeration value="top"></enumeration>
    		<enumeration value="bottom"></enumeration>
    		<enumeration value="left"></enumeration>
    		<enumeration value="right"></enumeration>
    		<enumeration value="center"></enumeration>
    		
    	</restriction>
    </simpleType>


    <simpleType name="Direction">
    	<restriction base="string">
    		<enumeration value="north"></enumeration>
    		<enumeration value="northeast"></enumeration>
    		<enumeration value="east"></enumeration>
    		<enumeration value="southeast"></enumeration>
    		<enumeration value="south"></enumeration>
    		<enumeration value="southwest"></enumeration>
    		<enumeration value="west"></enumeration>
    		<enumeration value="northwest"></enumeration>
    		<enumeration value="center"></enumeration>
    		<enumeration value="northnortheast"></enumeration>
    		<enumeration value="eastnortheast"></enumeration>
    		<enumeration value="eastsoutheast"></enumeration>
    		<enumeration value="northnorthwest"></enumeration>
    		<enumeration value="southsoutheast"></enumeration>
    		<enumeration value="southsouthwest"></enumeration>
    		<enumeration value="westsouthwest"></enumeration>
    		<enumeration value="westnortwest"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="SyntaxeVal">
    	<restriction base="string">
    		<enumeration value="inKora"></enumeration>
    		<enumeration value="inEshu"></enumeration>
    	</restriction>
    </simpleType>
    
    
     <simpleType name="Alignment">
    	<restriction base="string">
    		<enumeration value="left"></enumeration>
    		<enumeration value="right"></enumeration>
    		<enumeration value="center"></enumeration>
    	</restriction>
    </simpleType>
    
      <simpleType name="UnderlinedValue">
    	<restriction base="int">
    		<enumeration value="0"></enumeration>
    		<enumeration value="1"></enumeration>
    		<enumeration value="2"></enumeration>
    	</restriction>
    </simpleType>
    
   
</schema>

<!-- Alterar Steriotypes e ver  a label que ao aumentar a letra não está a redemensionar -->

=== mooshak-dcc/mooshak-2/WebContent/WEB-INF/classes/pt/up/fc/dcc/eshu/client/eshugwt/config2/activity.xml
<?xml version="1.0" encoding="UTF-8"?>
<dl2 xmlns="http://www.example.org/EshuConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/EshuConfig DL2.xsd ">
  <style>
    <editorStyle width="900" height="500" borderWidth="1" 
          borderColor="#000" background="white"  
          gridVisible="false" gridColorLine="#c0c0c0"/>
    
    <toolbarStyle width="500" height="300" borderWidth="1"
       				borderColor="black" background="WhiteSmoke"
       				position="vertical"  />
     <windowsProperties disabled="false" startVisible="false"/>  				
  </style>
  <diagram extension="" name="">
    
   
    
    
    
    <nodeTypes>
      <type>Action</type>
      <variant>Action</variant>
      <label alignment="center" defaultValue="Action" disabled="false" firstLetterCase="lowercase" letterCase="lowercase" pattern="(\w+)" position="center" marginHeight="0" marginWidth="0" underlined="0"  textColor="black" textFont="11px Arial" >
        <field name="name" value="1"/>
      </label>
      <isConfigurable>true</isConfigurable>
      <includeElement>false</includeElement>
       <rotation>false</rotation>
      <infoUrlNode>
        <url>https://www.tutorialspoint.com/uml/uml_basic_notations.htm</url>
      </infoUrlNode>
       <handlers> 
         <handler  position="northwest"/> 
         <handler  position="northeast"/>
         <handler  position="southeast"/>
         <handler  position="southwest"/> 
      </handlers>
      <anchors> 
         <anchor  position="north"/>
         <anchor  position="south"/> 
          <anchor  position="east"/>
          <anchor  position="west"/> 
      </anchors>
      <propertiesNode>
         <property name="type" type="String" typeShow="input" disabled="true" impExp="true" view="true"  />
	      <property name="id" type="Number" typeShow="input" disabled="true" impExp="true" view="true" /> 
          <property name="x" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="y" type="Number" typeShow="input" disabled="false" impExp="true" view="true" />
	      <property name="width" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="height" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="label" type="String" typeShow="input" disabled="false" impExp="true" view="true"/> 
      </propertiesNode>
       <featuresNode>
        </featuresNode>
      <nodeStyle autoresize="false" height="30" iconTollbarSVGPath="./image/Activity/ActionIcon.svg" imgSVGPath="./image/Activity/Action.svg" width="60"/>
      <nodeValidation allAnchorsConnect="false" degreeIn="unbounded" degreeOut="unbounded">
        <connects>
          <connect max="unbounded" min="0" to="Component" with="Activation"/>
        </connects>
      </nodeValidation>
    </nodeTypes>
    
    
    <nodeTypes>
      <type>Activity</type>
      <variant>Activity</variant>
      <label alignment="center" defaultValue="Activity" disabled="false" firstLetterCase="lowercase" letterCase="lowercase" pattern="(\w+)" position="center" marginHeight="0" marginWidth="0"  underlined="0"  textColor="black" textFont="11px Arial" >
        <field name="name" value="1"/>
      </label>
      <isConfigurable>true</isConfigurable>
      <includeElement>false</includeElement>
       <rotation>false</rotation>
      <infoUrlNode>
        <url>https://www.tutorialspoint.com/uml/uml_basic_notations.htm</url>
      </infoUrlNode>
       <handlers> 
         <handler  position="northwest"/> 
         <handler  position="northeast"/>
         <handler  position="southeast"/>
         <handler  position="southwest"/> 
      </handlers>
      <anchors> 
         <anchor  position="north"/>
         <anchor  position="south"/> 
          <anchor  position="east"/>
          <anchor  position="west"/> 
      </anchors>
      <propertiesNode>
         <property name="type" type="String" typeShow="input" disabled="true" impExp="true" view="true"  />
	      <property name="id" type="Number" typeShow="input" disabled="true" impExp="true" view="true" /> 
          <property name="x" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="y" type="Number" typeShow="input" disabled="false" impExp="true" view="true" />
	      <property name="width" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="height" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="label" type="String" typeShow="input" disabled="false" impExp="true" view="true"/> 
      </propertiesNode>
       <featuresNode>
        </featuresNode>
      <nodeStyle autoresize="false" height="40" iconTollbarSVGPath="./image/Activity/ActivityIcon.svg" imgSVGPath="./image/Activity/Activity.svg" width="100"/>
      <nodeValidation allAnchorsConnect="false" degreeIn="unbounded" degreeOut="unbounded">
        <connects>
          <connect max="unbounded" min="0" to="Component" with="Activation"/>
        </connects>
      </nodeValidation>
    </nodeTypes>
    
    
    
     <nodeTypes>
      <type>Decision</type>
      <variant>Decision</variant>
      <label alignment="center" defaultValue="" disabled="true" firstLetterCase="lowercase" letterCase="lowercase" pattern="(\w+)" position="center" marginHeight="0" marginWidth="0" underlined="0"  textColor="black" textFont="11px Arial" >
        <field name="name" value="1"/>
      </label>
      <isConfigurable>true</isConfigurable>
      <includeElement>false</includeElement>
       <rotation>false</rotation>
      <infoUrlNode>
        <url>https://www.tutorialspoint.com/uml/uml_basic_notations.htm</url>
      </infoUrlNode>
      <handlers> 
         <handler  position="northwest"/> 
         <handler  position="northeast"/>
         <handler  position="southeast"/>
         <handler  position="southwest"/> 
      </handlers>
      <anchors> 
         <anchor  position="north"/>
         <anchor  position="south"/> 
          <anchor  position="east"/>
          <anchor  position="west"/> 
      </anchors>
      <propertiesNode>
         <property name="type" type="String" typeShow="input" disabled="true" impExp="true" view="true"  />
	      <property name="id" type="Number" typeShow="input" disabled="true" impExp="true" view="true" /> 
          <property name="x" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="y" type="Number" typeShow="input" disabled="false" impExp="true" view="true" />
	      <property name="width" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="height" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="label" type="String" typeShow="input" disabled="false" impExp="true" view="true"/> 
      </propertiesNode>
       <featuresNode>
        </featuresNode>
      <nodeStyle autoresize="false" height="40" iconTollbarSVGPath="./image/Activity/DecisionIcon.svg" imgSVGPath="./image/Activity/Decision.svg" width="40"/>
      <nodeValidation allAnchorsConnect="false" degreeIn="unbounded" degreeOut="unbounded">
        <connects>
          <connect max="unbounded" min="0" to="Component" with="Decision"/>
        </connects>
      </nodeValidation>
    </nodeTypes>
    
     <nodeTypes>
      <type>Initial</type>
      <variant>Initial</variant>
      <label alignment="center" defaultValue="" disabled="true" firstLetterCase="lowercase" letterCase="lowercase" pattern="(\w+)" position="center" marginHeight="0" marginWidth="0" underlined="0"  textColor="black" textFont="11px Arial" >
        <field name="name" value="1"/>
      </label>
      <isConfigurable>true</isConfigurable>
      <includeElement>false</includeElement>
       <rotation>false</rotation>
      <infoUrlNode>
        <url>https://www.tutorialspoint.com/uml/uml_basic_notations.htm</url>
      </infoUrlNode>
       <handlers> 
         <handler  position="northwest"/> 
         <handler  position="northeast"/>
         <handler  position="southeast"/>
         <handler  position="southwest"/> 
      </handlers>
      <anchors> 
         <anchor  position="north"/>
         <anchor  position="south"/> 
          <anchor  position="east"/>
          <anchor  position="west"/> 
      </anchors>
      <propertiesNode>
         <property name="type" type="String" typeShow="input" disabled="true" impExp="true" view="true"  />
	      <property name="id" type="Number" typeShow="input" disabled="true" impExp="true" view="true" /> 
          <property name="x" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="y" type="Number" typeShow="input" disabled="false" impExp="true" view="true" />
	      <property name="width" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="height" type="Number" typeShow="input" disabled="false" impExp="true" view="true" /> 
	      <property name="label" type="String" typeShow="input" disabled="false" impExp="true" view="true"/> 
      </propertiesNode>
       <featuresNode>
        </featuresNode>
      <nodeStyle autoresize="false" height="35" iconTollbarSVGPath="./image/Activity/InitialIcon.svg" imgSVGPath="./image/Activity/Initial.svg" width="35"/>
      <nodeValidation allAnchorsConnect="false" degreeIn="unbounded" degreeOut="unbounded">
        <connects>
          <connect max="unbounded" min="0" to="Component" with="Decision"/>
        </connects>
      </nodeValidation>
    </nodeTypes>
        
  
      <nodeTypes>
      <type>Final</type>
      <variant>Initial</variant>
